kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{APP_NAME}}
  namespace: paas-dev

  labels:
    dce.daocloud.io/app: zipkinserver
    dce.daocloud.io/component: {{APP_NAME}}

spec:
  replicas: 2
  selector:
    matchLabels:
      dce.daocloud.io/component: {{APP_NAME}}
  template:
    metadata:
      name: {{APP_NAME}}
      labels:
        dce.daocloud.io/app: {{APP_NAME}}
        dce.daocloud.io/component: {{APP_NAME}}
    spec:
      containers:
        - name: {{APP_NAME}}
          image: '172.16.43.34/public/zipkin:2.19'
          env:
            - name: STORAGE_TYPE
              value: elasticsearch
            - name: ES_INDEX
              value: zipkin
            - name: JAVA_OPTS
              value: -server -Xms2G -Xmx3G -Xss256k -Xmn500m -Dlogging.level.zipkin=WARN -Dlogging.level.zipkin2=WARN
            - name: XMAX
              value: 2G
            - name: ES_HOSTS
              value: '172.16.43.28:9200,172.16.43.29:9200,172.16.43.30:9200'
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: '172.16.43.25:9092,172.16.43.26:9092,172.16.43.27:9092'
          resources:
            limits:
              cpu: '1'
              memory: '2147483648'
            requests:
              cpu: '1'
              memory: '2147483648'

          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
