FROM docker.io/openjdk:8-jre-alpine

ARG version

# Rocketmq version
ENV ROCKETMQ_VERSION 4.3.0

ENV ROCKETMQ_HOME  /rocketmq/rocketmq-home

WORKDIR  ${ROCKETMQ_HOME}
RUN mkdir -p /rocketmq/rocketmq-home
RUN mkdir -p \
		/rocketmq/logs \
	    /rocketmq/store


COPY rocketmq-all-4.3.0-bin-release.zip /rocketmq/rocketmq-home/


RUN  unzip  rocketmq-all-4.3.0-bin-release.zip

RUN  mv rocketmq-all-4.3.0-bin-release/*  .
RUN  rm -rf rocketmq-all-4.3.0-bin-release
RUN  rm -f  rocketmq-all-4.3.0-bin-release.zip


#replace log path
COPY logback_broker.xml /rocketmq/rocketmq-home/conf/
COPY logback_namesrv.xml /rocketmq/rocketmq-home/conf/
COPY logback_tools.xml /rocketmq/rocketmq-home/conf/
COPY logback_filtersrv.xml /rocketmq/rocketmq-home/conf/


RUN chmod +x bin/mqnamesrv
CMD  cd bin && export JAVA_OPT=" -Duser.home=/rocketmq" && sh mqnamesrv


EXPOSE 9876
VOLUME /rocketmq
