FROM 172.16.44.49/public/jdk:8-shanghai

MAINTAINER wuzuzuquan

ENV ROCKETMQ_HOME  /rocketmq/rocketmq-home
ENV MEMORY "-Xms2g -Xmx2g -Xmn1g"
ENV NAMESRV "localhost:9876"
ENV POD_IP 127.0.0.1

WORKDIR  ${ROCKETMQ_HOME}
RUN mkdir -p /rocketmq/rocketmq-home
RUN mkdir -p /rocketmqdata


COPY rocketmq-all-4.6.0-bin-release.zip /rocketmq/rocketmq-home/
RUN  unzip  rocketmq-all-4.6.0-bin-release.zip

RUN  mv rocketmq-all-4.6.0-bin-release/*  .
RUN  rm -rf rocketmq-all-4.6.0-bin-release
RUN  rm -f  rocketmq-all-4.6.0-bin-release.zip

#replace log path
COPY logback_broker.xml /rocketmq/rocketmq-home/conf/
COPY logback_namesrv.xml /rocketmq/rocketmq-home/conf/
COPY logback_tools.xml /rocketmq/rocketmq-home/conf/
COPY logback_filtersrv.xml /rocketmq/rocketmq-home/conf/

COPY 2m-2s-sync/broker-a.properties /rocketmq/rocketmq-home/conf/2m-2s-sync
COPY 2m-2s-sync/broker-a-s.properties /rocketmq/rocketmq-home/conf/2m-2s-sync
COPY 2m-2s-sync/broker-b.properties /rocketmq/rocketmq-home/conf/2m-2s-sync
COPY 2m-2s-sync/broker-b-s.properties /rocketmq/rocketmq-home/conf/2m-2s-sync



RUN export JAVA_OPT=" -Duser.home=/rocketmq"


COPY set-jvm.sh /rocketmq/rocketmq-home/docker-entrypoint.sh
RUN chmod +x /rocketmq/rocketmq-home/docker-entrypoint.sh
ENTRYPOINT ["/rocketmq/rocketmq-home/docker-entrypoint.sh"]


CMD   sh bin/mqbroker -n namesrv:9876

EXPOSE 10909 10911


