setup.kibana:
  host: "http://172.16.43.31:31937"
filebeat.inputs:
- type: log
  paths:
  - /root/*/*/*.log
  - /root/*/*/*/*.log
  fields:
    topic: app-log

- type: log
  paths:
  - /root/nginx/*error.log
  fields:
    topic: nginx-log
    level: error

- type: log
  paths:
  - /root/nginx/*access.log
  fields:
    topic: nginx-log
    level: info
  processors:
    - drop_event:
       when:
          or:
            - contains:
                message: "kibana"
            - contains:
                message: "KeepAliveClient"
            - contains:
                message: "TCP200000"

- type: docker
  containers.ids:
  - "*"
  fields:
    topic: containers-log
  processors:
  - add_kubernetes_metadata:
      host: ${NODE_NAME}
      in_cluster: true

output.kafka:
  enabled: true
  hosts: ["kafka-0.dao-efk:9092", "kafka-1.dao-efk:9092", "kafka-2.dao-efk:9092"]
  topic: '%{[fields.topic]}'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000