apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:

  labels:
    k8s-app: filebeat
  name: filebeat
  namespace: kube-system

spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      containers:
      - args:
        - -c
        - /etc/filebeat.yml
        - -e
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: 172.16.44.49/daocloud/filebeat:7.3.2
        imagePullPolicy: IfNotPresent
        name: filebeat
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/filebeat.yml
          name: config
          readOnly: true
          subPath: filebeat.yml
        - mountPath: /usr/share/filebeat/data
          name: data
        - mountPath: /var/log/containers
          name: var-log-containers
          readOnly: true
        - mountPath: /var/log/pods
          name: var-log-pods
          readOnly: true
        - mountPath: /var/lib/docker/containers
          name: var-lib-docker-containers
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: varrundockersock
          readOnly: true
        - mountPath: /root
          name: app-log
          readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: filebeat
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 384
          name: filebeat-config
        name: config
      - hostPath:
          path: /var/log/containers
          type: ""
        name: var-log-containers
      - hostPath:
          path: /var/log/pods
          type: ""
        name: var-log-pods
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: var-lib-docker-containers
      - hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
        name: data
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: varrundockersock
      - hostPath:
          path: /var/log
          type: ""
        name: app-log
  templateGeneration: 5
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

