kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{APP_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      dce.daocloud.io/component: {{APP_NAME}}
  template:
    metadata:
      name: {{APP_NAME}}
      labels:
        dce.daocloud.io/app: {{APP_NAME}}
        dce.daocloud.io/component: {{APP_NAME}}

    spec:
      containers:
        - name: mqnode
          image: '172.16.44.49/public/rabbitmq:3.8.2'
          volumeMounts:
              - name: datadir
                mountPath: /var/lib/rabbitmq
          env:
            - name: MEMORY
              value: "-Xms2G -Xmx2G -Xmn1G"
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 2Gi
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
          tty: true
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: '5Gi'
        storageClassName: huafa
        volumeMode: Filesystem
  podManagementPolicy: OrderedReady
  serviceName: {{APP_NAME}}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 3
---


apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-service
  labels:
    dce.daocloud.io/app: {{APP_NAME}}
spec:
  ports:
    - name: servicename
      protocol: TCP
      port: 5672
      targetPort: 5672
  selector:
    dce.daocloud.io/component: {{APP_NAME}}
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None

