FROM alpine:latest
MAINTAINER wuzuquan

RUN mkdir -p /consul/data && \
    mkdir -p /consul/config

VOLUME /consul
ADD consul /bin

EXPOSE 8300 53

# Serf LAN and WAN (WAN is used only by Consul servers) are used for gossip between
# Consul agents. LAN is within the datacenter and WAN is between just the Consul
# servers in all datacenters.
EXPOSE 8301 8301/udp 8302 8302/udp

# HTTP and DNS (both TCP and UDP) are the primary interfaces that applications
# use to interact with Consul.
EXPOSE 8500 8600 8600/udp

CMD ["consul","agent","-server","-ui", "-bootstrap-expect","3","-data-dir","/consul/data","-config-dir","/consul/config","-join","10.42.174.216", "-client", "0.0.0.0"]
