FROM 172.16.44.49/public/alpine:latest
MAINTAINER wuzuquan
#设置时区
COPY shanghai.timezone  /etc/localtime
RUN  echo 'Asia/Shanghai' >/etc/timezone

RUN mkdir -p /consul/

VOLUME /consul
ADD consul /usr/bin
WORKDIR /usr/bin
run chmod 777 /usr/bin/consul

EXPOSE 8300 53

# Serf LAN and WAN (WAN is used only by Consul servers) are used for gossip between
# Consul agents. LAN is within the datacenter and WAN is between just the Consul
# servers in all datacenters.
EXPOSE 8301 8301/udp 8302 8302/udp

# HTTP and DNS (both TCP and UDP) are the primary interfaces that applications
# use to interact with Consul.
EXPOSE 8500 8600 8600/udp

CMD ["consul","agent","-server","-ui", "-bootstrap-expect","1","-data-dir","/consul", "-client", "0.0.0.0"]
