FROM 172.16.44.49/public/nginx:1.17
MAINTAINER wuzuquan

#设置时区
COPY shanghai.timezone  /etc/localtime 
RUN  echo 'Asia/Shanghai' >/etc/timezone 

ENV  REDISPASSWORD  default
ENV  MAXMEM  500MB


COPY set.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx -g 'daemon off;'"]

EXPOSE 80

