kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-rbd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ceph.com/rbd
parameters:
  monitors: 172.16.44.4:6789,172.16.44.5:6789,172.16.44.6:6789
  adminId: admin
  adminSecretName: ceph-secret-admin-wzq
  adminSecretNamespace: kube-system
  pool: test-rbd
  userId: wzq
  userSecretName: ceph-secret-wzq
  imageFormat: "2"
  imageFeatures: layering


---

apiVersion: v1
data:
  key: QVFCSW52RmQ1RXY3Q0JBQTBpZG1ZSTdZUmJMRE90RCttd3E4T3c9PQ==
       
       
kind: Secret
metadata:
  name: ceph-secret-admin-wzq
  namespace: kube-system
type: kubernetes.io/rbd


---

apiVersion: v1
data:
  key: QVFEMHR2RmRPVkVRSHhBQUp2WjQ0d2hzNnhZckxxSHVhOHNNU1E9PQ==
kind: Secret
metadata:
  name: ceph-secret-wzq
type: kubernetes.io/rbd

