FROM 172.16.44.49/wuzuquan/redis:5.0-offical
MAINTAINER wuzuquan
RUN mkdir  -p /redis/data
VOLUME /redis/data
WORKDIR /redis/data

#设置时区
COPY shanghai.timezone  /etc/localtime 
RUN  echo 'Asia/Shanghai' >/etc/timezone 

ENV  REDISPASSWORD  default
ENV  MAXMEM  500MB
COPY redis.conf /redis.conf

COPY set-redis-pass.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD [ "redis-server", "/redis.conf" ]

EXPOSE 6000
EXPOSE 16000

